version: "3.8"
services:
    schemaspy:
        image: schemaspy/schemaspy:6.1.0
        volumes:
            - ./erd-original:/output
            - ./docker/schemaspy/drivers:/drivers
        depends_on:
            db:
                condition: service_healthy
        command: >
            java -jar schemaspy.jar
            -t pgsql
            -host db
            -port 5432
            -db ${DB_DATABASE}_org
            -s public
            -u ${DB_USERNAME}
            -p ${DB_PASSWORD}
